export const SITE = {
  name: "fi.artistry",
  artist: "Firat Yucedag",
  tagline: "Every line, every detail tells your unique story.",
  description:
    "Firat Yucedag — an internationally travelling fine line and micro-realism tattoo artist. Custom, story-driven pieces drawn from scratch, with a year-round residency in İzmir and regular guest spots across Europe.",
  shortDescription:
    "International fine line & micro-realism tattoo artist. Custom, story-driven designs. Residency in İzmir, guest spots across Europe.",
  url: "https://www.fiartistry.com",
  email: "hello@fiartistry.com",
  phone: "+90 (544) 663 69 23",
  phoneE164: "+905446636923",
  instagram: "https://instagram.com/firatyucedag",
  instagramHandle: "@firatyucedag",
  instagramDM: "https://ig.me/m/firatyucedag",
  pinterest: "https://pinterest.com/fi.artistry",
  pinterestHandle: "fi.artistry",
  bookingUrl: "/booking",
  location: {
    city: "İzmir",
    region: "İzmir",
    country: "Türkiye",
    countryCode: "TR",
  },
  areasServed: [
    "Germany",
    "Netherlands",
    "France",
    "Belgium",
    "Switzerland",
    "Sweden",
    "Denmark",
    "Austria",
    "Spain",
    "Portugal",
    "Italy",
    "United Kingdom",
    "Türkiye",
  ],
  styles: [
    "Fine Line",
    "Micro-Realism",
    "Black & Grey",
    "Fine Line Portraits",
    "Small & Delicate Tattoos",
  ],
  keywords: [
    "fine line tattoo",
    "micro realism tattoo",
    "micro-realism tattoo artist",
    "custom tattoo design",
    "tattoo artist Europe",
    "European tattoo tour",
    "guest spot tattoo artist",
    "fine line tattoo Germany",
    "Hamburg tattoo artist",
    "Munich tattoo artist",
    "Berlin tattoo artist",
    "Amsterdam tattoo artist",
    "Paris tattoo artist",
    "Barcelona tattoo artist",
    "İzmir tattoo artist",
    "Turkey tattoo artist",
    "black and grey tattoo",
    "delicate tattoo",
    "story tattoo",
    "Firat Yucedag",
    "fi.artistry",
    "fi artistry",
  ],
} as const;

export const NAV = [
  { href: "/#me", label: ".me story", badge: null },
  { href: "/works", label: ".works", badge: null },
  { href: "/design", label: ".design", badge: "new" as const },
  { href: "/guest", label: ".guest", badge: null },
  { href: "/#shop", label: ".shop", badge: null },
] as const;
